export const projects = [
  {
    id: 1,
    title: "Portfolio VSCode",
    img: "/portfolio2.png",
    desc: "Mon portfolio aux couleurs de VsCode. Souriez, vous-êtes ici :)",
    tags: ["nextjs", "tailwindcss", "react", "clerk", "express"],
    source: "https://github.com/ruddyautem/Portfolio",
    demo: "https://autem.dev",
  },
  {
    id: 2,
    title: "Style-D",
    img: "/styled.jpg",
    desc: "Plateforme d'E-Commerce fonctionnelle. Ajoutez vos articles dans le panier et payez avec Stripe!",
    tags: [
      "react",
      "firebase",
      "styled-components",
      "zustand",
      "material-ui",
      "axios",
    ],
    source: "https://github.com/ruddyautem/style-D/",
    demo: "https://style-d.vercel.app",
  },
  {
    id: 3,
    title: "OhMyBlog!",
    img: "/ohmyblog.png",
    desc: "Plateforme de création de blogs moderne, responsive et sécurisée. Authentification gérée via Clerk, API robuste construite avec Express.js",
    tags: ["react", "axios", "tailwindcss", "clerk"],
    source: "https://github.com/ruddyautem/ohmyblog/",
    demo: "https://ohmyblog.autem.dev",
  },
  {
    id: 4,
    title: "DressCode Ecommerce",
    img: "/dresscode.png",
    desc: "Plateforme e-commerce avec Next.js et Sanity, un CMS headless flexible qui permet de gérer facilement les produits et le contenu via une interface intuitive.",
    tags: ["nextjs", "sanity", "typescript", "tailwindcss", "clerk"],
    source: "https://github.com/ruddyautem/DressCode",
    demo: "https://dresscode-ecommerce.vercel.app",
  },
  {
    id: 5,
    title: "Laxxy",
    img: "/laxxy.png",
    desc: "Messagerie inspirée de Slack. Connectez-vous, rejoignez ou créez un canal, et partagez des messages consultables en temps réel par les autres utilisateurs",
    tags: ["react", "redux", "styled-components", "firebase"],
    source: "https://github.com/ruddyautem/laxxy",
    demo: "https://laxxy.vercel.app",
  },
  {
    id: 6,
    title: "CoolMail",
    img: "/coolmail.png",
    desc: "Boîte mail optimisée pour l'envoi de messages en local. Connexion via Google et stockage des messages  avec  Firebase",
    tags: ["react", "styled-components", "firebase"],
    source: "https://github.com/ruddyautem/CoolMail",
    demo: "https://coolmail.vercel.app",
  },
  {
    id: 7,
    title: "GPT-3",
    img: "/gpt3.jpg",
    desc: "Interface visuelle d'une plateforme de tutoriels GPT-3",
    tags: ["react"],
    source: "https://github.com/ruddyautem/gpt3",
    demo: "https://gpt3-v2.vercel.app",
  },
];
