import Menu from '@/components/Menu/Menu';
import './globals.css';
import { Inter } from 'next/font/google';
import Footer from '@/components/Footer/Footer';
import Sidebar from '@/components/Sidebar/Sidebar';
import Explorer from '@/components/Explorer/Explorer';
import Tabsbar from '@/components/Tabsbar/Tabsbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};



export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='h-screen flex flex-col h-'>
        <Menu className='' />
        <div className='flex flex-1'>
          <div className='flex'>
            <Sidebar className='' />
            <Explorer className='' />
          </div>
          <div className='flex flex-col flex-1 overflow-hidden'>
            <Tabsbar className='' />
            <div className='overflow-y-hidden h-[calc(100vh-84px)] px-4'>{children}</div>
          </div>
        </div>
        <Footer className='' />
      </body>
    </html>
  );
}
