export const skills = {
  frontend: [
    { skill: 'HTML', icon: '/html52.svg' },
    { skill: 'CSS', icon: '/css.svg' },
    { skill: 'JavaScript', icon: '/js.svg' },
    { skill: 'TypeScript', icon: '/typescript.svg' },
    { skill: 'React', icon: '/react.svg' },
    { skill: 'Next.js', icon: '/nextjs.svg' },
    { skill: 'Vue.js', icon: '/vuejs.svg' },
    { skill: 'Vite', icon: '/vite.svg' },
    { skill: 'TailwindCSS', icon: '/tailwind.svg' },
    { skill: 'Styled Components', icon: '/styled.svg' },
    { skill: 'SASS', icon: '/sass.svg' },
    { skill: 'Bootstrap', icon: '/bootstrap.svg' },
    { skill: 'Shadcn', icon: '/shadcn.svg' },
    { skill: 'Redux', icon: '/redux.svg' },
    { skill: 'Zustand', icon: '/zustand.svg' }
  ],
  backend: [
    { skill: 'Node.js', icon: '/nodejs.svg' },
    { skill: 'Express.js', icon: '/express.svg' },
    { skill: 'MongoDB', icon: '/mongodb.svg' },
    { skill: 'MySQL', icon: '/mysql.svg' },
    { skill: 'Firebase', icon: '/firebase.svg' },
    { skill: 'Prisma', icon: '/prisma.svg' },
    { skill: 'Zod', icon: '/zod.svg' },
    { skill: 'Clerk', icon: '/clerk.svg' },
  ],
  tools: [
    { skill: 'Git', icon: '/git.svg' },
    { skill: 'GitHub', icon: '/github.svg' },
    { skill: 'VSCode', icon: '/vsclogo.svg' },
    { skill: 'Cursor', icon: '/cursor.svg' },
    { skill: 'Postman', icon: '/postman.svg' },
    { skill: 'SSH', icon: '/ssh.svg' },
    { skill: 'Vercel', icon: '/vercel2.svg' },
    { skill: 'Netlify', icon: '/netlify.svg' },
    { skill: 'Heroku', icon: '/heroku.svg' },
    { skill: 'Dokploy', icon: '/dokploy.svg' },
    { skill: 'Sanity', icon: '/sanity2.svg' },
    { skill: 'AI', icon: '/ai.svg' },
  ],
};