export const skills = {
  frontend: [
    { skill: "HTML", icon: "/html52.svg" },
    { skill: "CSS", icon: "/css.svg" },
    { skill: "JavaScript", icon: "/js.svg" },
    { skill: "React", icon: "/react.svg" },
    { skill: "TypeScript", icon: "/typescript.svg" },
    { skill: "Next.js", icon: "/nextjs.svg" },
    { skill: "Vite", icon: "/vite.svg" },
    { skill: "TailwindCSS", icon: "/tailwind.svg" },
    { skill: "Styled Components", icon: "/styled.svg" },
    { skill: "SASS", icon: "/sass.svg" },
    { skill: "Redux", icon: "/redux.svg" },
    { skill: "Bootstrap", icon: "/bootstrap.svg" },
    { skill: "Shadcn", icon: "/shadcn.svg" },
  ],
  backend: [
    { skill: "MongoDB", icon: "/mongodb.svg" },
    { skill: "Firebase", icon: "/firebase.svg" },
    { skill: "Node.js", icon: "/nodejs.svg" },
    { skill: "Express.js", icon: "/express.svg" },
    { skill: "Prisma", icon: "/prisma.svg" },
    { skill: "Clerk", icon: "/clerk.svg" },
    { skill: "Zustand", icon: "/zustand.svg" },
    { skill: "MySQL", icon: "/mysql.svg" },
  ],
  tools: [
    { skill: "Git", icon: "/git.svg" },
    { skill: "GitHub", icon: "/github.svg" },
    { skill: "Vercel", icon: "/vercel2.svg" },
    { skill: "Sanity", icon: "/sanity2.svg" },
    { skill: "Heroku", icon: "/heroku.svg" },
    { skill: "Netlify", icon: "/netlify.svg" },
    { skill: "VSCode", icon: "/vsclogo.svg" },
    { skill: "Postman", icon: "/postman.svg" },
    { skill: "SSH", icon: "/ssh.svg" },
    { skill: "IA", icon: "/ai.svg" },
  ],
};
